languageCode = "en"
languageName = "English"
weight = 1
title = "Existential Heroism Institute"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2, 2006"
logo = "img/EHI Header Icon.png"

[author]
name = "Existential Heroism Institute"
headline = "The start of the existential hero's journey."
bio = "bio"
links = [ { discord = "https://discord.gg/N7SWWMbWFD" }, { instagram = "https://www.instagram.com/x_heroism" }, { twitter = "https://x.com/X_heroism" }, { youtube = "https://www.youtube.com/@ExistentialHeroismInstitute" } ]
