languageCode = "en"
languageName = "English"
weight = 1
title = "Existential Heroism Institute"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2, 2006"
logo = "img/EHI Header Icon.png"

[author]
name = "Existential Heroism Institute"
headline = "The start of the existential hero's journey."
bio = "bio"
links = [ { discord = "https://discord.gg/N7SWWMbWFD" }, { instagram = "x_heroism" }, { twitter = "x_heroism" }, { youtube = "@ExistentialHeroismInstitute" } ]
