[[main]]
name = "Articles"
pageRef = "articles"
identifier = "6uJEBm8A5N"
weight = 10

[[main]]
name = "Resources"
weight = 20

[[main]]
name = "Books"
parent = "Resources"
pageRef = "reading-list"
weight = 10

[[main]]
name = "Online Resources"
parent = "Resources"
pageRef = "online-resources.md"
weight = 20

# [[main]]
# name = "Projects"
# pageRef = "projects"
# identifier = "kkJKueLaXx"
# weight = 30

[[main]]
name = "About Us"
pageRef = "about-us.md"
identifier = "ZIDnbd9eVx"
weight = 40

[[main]]
name = "Contact"
pageRef = "contact.md"
identifier = "W1at3TJvyM"
weight = 50

[[footer]]
none = "none"
